sudo: false

language: cpp

os:
#  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libboost-test-dev

# Install Boost 1.60 on OSX, linked with libc++ for C++11 support
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink boost; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget 'https://github.com/Malvineous/travis-homebrew-bottle/releases/download/boost-1.60-cxx11/boost-1.60.0_2.mavericks.bottle.tar.gz'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install *.bottle.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CXX" == "g++" ]]; then export CXXFLAGS="-stdlib=libc++"; fi

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - ./autogen.sh

script:
  - ./configure && make && make V=1 check
